//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HE_SchlumbergerWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wine
    {
        public int id { get; set; }
        public string country { get; set; }
        public string description { get; set; }
        public string designation { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> price { get; set; }
        public string province { get; set; }
        public string region_1 { get; set; }
        public string region_2 { get; set; }
        public string variety { get; set; }
        public string winery { get; set; }
    }
}
